apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jfrog-artifactory-jcr
  namespace: gitops-resources
spec:
  destination:
    namespace: artifactory-jcr2
    server: https://kubernetes.default.svc
  project: gitops-resources
  source:
    path: ./components/jfrog-artifactory-jcr
    repoURL: https://github.com/redhat-appstudio/rhtap-services-gitops
    targetRevision: main
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true

