apiVersion: v1
data:
  postgresql-password: SmxJbVdhb0pRdw==
  postgresql-postgres-password: QVIySmVsVHp1Zg==
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: jfrog-container-registry
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-10.3.18
  name: jfrog-container-registry-postgresql
  namespace: artifactory-jcr2
type: Opaque
---
apiVersion: v1
data:
  access.config.patch.yml: c2VjdXJpdHk6CiAgdGxzOiBmYWxzZQo=
  binarystore.xml: PCEtLSBGaWxlIHN5c3RlbSBmaWxlc3RvcmUgLS0+Cjxjb25maWcgdmVyc2lvbj0idjEiPgogICAgPGNoYWluPiA8IS0tdGVtcGxhdGU9ImZpbGUtc3lzdGVtIi0tPgogICAgICAgICAgICA8cHJvdmlkZXIgaWQ9ImZpbGUtc3lzdGVtIiB0eXBlPSJmaWxlLXN5c3RlbSIvPgogICAgPC9jaGFpbj4KPC9jb25maWc+
  system.yaml: CmFjY2VzczoKICBkYXRhYmFzZToKICAgIG1heE9wZW5Db25uZWN0aW9uczogODAKICBleHRyYUphdmFPcHRzOiB8CiAgICAtWFg6SW5pdGlhbFJBTVBlcmNlbnRhZ2U9MjAgLVhYOk1heFJBTVBlcmNlbnRhZ2U9NzAKICBydW5PbkFydGlmYWN0b3J5VG9tY2F0OiBmYWxzZQogIHRvbWNhdDoKICAgIGNvbm5lY3RvcjoKICAgICAgZXh0cmFDb25maWc6IGFjY2VwdENvdW50PSIxMDAiCiAgICAgIG1heFRocmVhZHM6IDUwCiAgICAgIHNlbmRSZWFzb25QaHJhc2U6IGZhbHNlCmFydGlmYWN0b3J5OgogIGRhdGFiYXNlOgogICAgbWF4T3BlbkNvbm5lY3Rpb25zOiA4MAogIHRvbWNhdDoKICAgIGNvbm5lY3RvcjoKICAgICAgZXh0cmFDb25maWc6IGFjY2VwdENvdW50PSI0MDAiCiAgICAgIG1heFRocmVhZHM6IDIwMAogICAgICBzZW5kUmVhc29uUGhyYXNlOiBmYWxzZQogICAgbWFpbnRlbmFuY2VDb25uZWN0b3I6CiAgICAgIHBvcnQ6IDgwOTEKZXZpZGVuY2U6CiAgZW5hYmxlZDogZmFsc2UKZnJvbnRlbmQ6CiAgc2Vzc2lvbjoKICAgIHRpbWVNaW51dGVzOiAiMzAiCmpmY29ubmVjdDoKICBlbmFibGVkOiBmYWxzZQpqZmNvbm5lY3Rfc2VydmljZToKICBlbmFibGVkOiBmYWxzZQptZXRhZGF0YToKICBkYXRhYmFzZToKICAgIG1heE9wZW5Db25uZWN0aW9uczogODAKb25lbW9kZWw6CiAgZW5hYmxlZDogZmFsc2UKcm91dGVyOgogIHNlcnZpY2VSZWdpc3RyeToKICAgIGluc2VjdXJlOiBmYWxzZQpydGZzOgogIGVuYWJsZWQ6IGZhbHNlCnNoYXJlZDoKICBkYXRhYmFzZToKICAgIGFsbG93Tm9uUG9zdGdyZXNxbDogZmFsc2UKICAgIGRyaXZlcjogb3JnLnBvc3RncmVzcWwuRHJpdmVyCiAgICB0eXBlOiBwb3N0Z3Jlc3FsCiAgICB1cmw6IGpkYmM6cG9zdGdyZXNxbDovL2pmcm9nLWNvbnRhaW5lci1yZWdpc3RyeS1wb3N0Z3Jlc3FsOjU0MzIvYXJ0aWZhY3RvcnkKICAgIHVzZXJuYW1lOiBhcnRpZmFjdG9yeQogIGV4dHJhSmF2YU9wdHM6IHwKICAgIC1EYXJ0aWZhY3RvcnkuZ3JhY2VmdWwuc2h1dGRvd24ubWF4LnJlcXVlc3QuZHVyYXRpb24ubWlsbGlzPTMwMDAwIC1EYXJ0aWZhY3RvcnkuYWNjZXNzLmNsaWVudC5tYXguY29ubmVjdGlvbnM9NTAKICBsb2dnaW5nOgogICAgY29uc29sZUxvZzoKICAgICAgZW5hYmxlZDogZmFsc2UKdG9wb2xvZ3k6CiAgZGF0YWJhc2U6CiAgICBtYXhPcGVuQ29ubmVjdGlvbnM6IDgwCiAgZW5hYmxlZDogdHJ1ZQogIGV4dHJhSmF2YU9wdHM6IHwKICAgIC1YWDpJbml0aWFsUkFNUGVyY2VudGFnZT0yMCAtWFg6TWF4UkFNUGVyY2VudGFnZT03MAogIHBvcnQ6IDgwMjAK
kind: Secret
metadata:
  labels:
    app: artifactory
    chart: artifactory-107.104.15
    component: artifactory
    heritage: Helm
    release: jfrog-container-registry
  name: jfrog-container-registry-artifactory-unified-secret
  namespace: artifactory-jcr2
type: Opaque

