apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: jfrog-container-registry
    app.kubernetes.io/name: postgresql
  name: jfrog-container-registry-postgresql-headless
  namespace: artifactory-jcr2
spec:
  ports:
  - name: tcp-postgresql
    port: 5432
    protocol: TCP
    targetPort: tcp-postgresql
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/instance: jfrog-container-registry
    app.kubernetes.io/name: postgresql
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: jfrog-container-registry
    app.kubernetes.io/name: postgresql
  name: jfrog-container-registry-postgresql
  namespace: artifactory-jcr2
spec:
  ports:
  - name: tcp-postgresql
    port: 5432
    protocol: TCP
    targetPort: tcp-postgresql
  selector:
    app.kubernetes.io/instance: jfrog-container-registry
    app.kubernetes.io/name: postgresql
    role: primary
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: artifactory
    component: artifactory
  name: jfrog-container-registry-artifactory
  namespace: artifactory-jcr2
spec:
  ports:
  - name: http-router
    port: 8082
    protocol: TCP
    targetPort: 8082
  - name: http-artifactory
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: artifactory
    component: artifactory

