---
artifactory:
  podSecurityContext:
    enabled: false
  containerSecurityContext:
    enabled: false

  artifactory:
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
    initContainers:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi

  nginx:
    enabled: false
    containerSecurityContext:
      enabled: false
    podSecurityContext:
      enabled: false

  postgresql:
    enabled: true
    auth:
      password: "a-strong-password"
    primary:
      podSecurityContext:
        enabled: false
      securityContext:
        enabled: false
      containerSecurityContext:
        enabled: false

