apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
resources:
  - statefulset.yaml
  - service.yaml
  - route-nexus-ui.yaml
  - route-nexus-docker.yaml
